FROM node:18

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

RUN npm install pg

COPY . .

ENV NODE_ENV production
RUN npm prune --production

RUN npm run build

EXPOSE 1337

CMD ["npm", "run", "start"]