FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

# remove dev dependencies
ENV NODE_ENV production
RUN npm prune --production

RUN npm run build
EXPOSE 3000

CMD ["npm", "run", "start"]